name: Snyk Security Scan

on:
  #push:
  #pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (Juice Shop is a Node.js project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Snyk scan
      - name: Snyk Scan
        uses: snyk/actions@v3
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Add your Snyk token as a secret in the GitHub repository

      # Optional: Upload Snyk results as an artifact
      - name: Upload Snyk Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-res.json
