name: SCA with Snyk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to be available..."
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop is ready!"
    
      # Step to check out the code
      - name: Checkout code
        uses: actions/checkout@v2

        # Step to set up Node.js (if using Node.js, adjust if necessary)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your version if different
  
        # Step to install dependencies
      - name: Install dependencies
        run: npm install
  
        # Step to install Snyk
      - name: Install Snyk
        run: npm install -g snyk
  
        # Step to run the Snyk test for dependencies
      - name: Run Snyk SCA scan 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --json > snyk-result.json || true
  
        # Step to install Snyk-to-HTML
      - name: Install Snyk-to-HTML
        run: npm install -g snyk-to-html
  
        # Step to convert JSON results to HTML
      - name: Generate HTML Report
        run: snyk-to-html -i snyk-result.json -o snyk-report.html
  
        # Step to upload the HTML report as an artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-html-report
          path: snyk-report.html
